package punktfunk

import "testing"

// TestParseTokenFile pins the real shape punktfunk writes. The env-file form is the one
// that matters: parsing it wrongly sends "PUNKTFUNK_MGMT_TOKEN=<token>" as the bearer and
// every authenticated method returns 401 — the exact failure a live bed run surfaced.
func TestParseTokenFile(t *testing.T) {
	const tok = "example-token-not-a-real-credential"
	for name, in := range map[string]string{
		"env-file form (what punktfunk 0.33.0-1 actually writes)": "PUNKTFUNK_MGMT_TOKEN=" + tok + "\n",
		"bare token":            tok + "\n",
		"trailing whitespace":   "  " + tok + "  \n\n",
		"quoted value":          `PUNKTFUNK_MGMT_TOKEN="` + tok + `"` + "\n",
		"single-quoted value":   "PUNKTFUNK_MGMT_TOKEN='" + tok + "'\n",
		"comment then env line": "# generated by punktfunk-host\nPUNKTFUNK_MGMT_TOKEN=" + tok + "\n",
		"CRLF line endings":     "PUNKTFUNK_MGMT_TOKEN=" + tok + "\r\n",
	} {
		if got := parseTokenFile(in); got != tok {
			t.Errorf("%s: parseTokenFile = %q, want %q", name, got, tok)
		}
	}
}

// TestParseTokenFilePrefersTheManagementKey — the host writes a sibling plugin-token, so
// if a file ever carries several keys the management one must win regardless of order.
func TestParseTokenFilePrefersTheManagementKey(t *testing.T) {
	in := "PUNKTFUNK_PLUGIN_TOKEN=plugin-one\nPUNKTFUNK_MGMT_TOKEN=mgmt-one\n"
	if got := parseTokenFile(in); got != "mgmt-one" {
		t.Errorf("parseTokenFile = %q, want the management token", got)
	}
	reversed := "PUNKTFUNK_MGMT_TOKEN=mgmt-one\nPUNKTFUNK_PLUGIN_TOKEN=plugin-one\n"
	if got := parseTokenFile(reversed); got != "mgmt-one" {
		t.Errorf("parseTokenFile (reversed) = %q, want the management token", got)
	}
}

func TestParseTokenFileEmpty(t *testing.T) {
	for _, in := range []string{"", "\n\n", "# only a comment\n", "PUNKTFUNK_MGMT_TOKEN=\n"} {
		if got := parseTokenFile(in); got != "" {
			t.Errorf("parseTokenFile(%q) = %q, want empty", in, got)
		}
	}
}
