// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package params

// The `punktfunk` plugin's OWN CUE schema — the typed plugin_input for the
// `punktfunk` check verb, which drives a punktfunk streaming host's management
// REST API (bearer token over HTTPS on 47990).
//
// SELF-CONTAINED by contract: it references NO base def, so it compiles standalone
// (both `cue exp gengotypes` and the host's load-gate compile) AND splices onto the
// base as `base ++ plugin`.
//
// Single source, used two ways:
//  1. GENERATE ../params/cue_types_gen.go via `cue exp gengotypes`, so the provider
//     decodes plugin_input into a TYPED struct rather than a hand-parsed map.
//  2. VALIDATE authored input AT RUNTIME — served over Describe, spliced by the host,
//     and every authored `punktfunk:` step's plugin_input checked against #PunktfunkInput.
type PunktfunkInput struct {
	// method — the operation (also the scalar-sugar primary, so `punktfunk: status`
	// desugars to {method: "status"}).
	//
	// Read methods are safe on any host; the mutating ones (pair-arm, approve, deny,
	// unpair, rename, access, end-game, action-invoke, scanner-toggle) change host
	// state and belong in `run:` steps, not `check:` steps.
	Method string `json:"method"`

	// host — the client-side `<host-ref>`: a saved host name, or host[:port]. Required
	// by every client method that names a host.
	Host string `json:"host,omitempty"`

	// probe — hosts-list only: add the live reachability check (`--probe`).
	Probe bool `json:"probe,omitempty"`

	// game — launch only: stream directly into a specific game id (`--game`).
	Game string `json:"game,omitempty"`

	// auto_approve — open only: `--yes`, auto-approving an unknown host. Documented
	// for automation; it trades a trust prompt for unattended operation, so it is opt-in
	// per step rather than implied.
	AutoApprove bool `json:"auto_approve,omitempty"`

	// client_bin — override the client binary. The Flatpak build is not on PATH and is
	// reached as `flatpak run --command=punktfunk io.unom.Punktfunk`.
	ClientBin string `json:"client_bin,omitempty"`

	// port — the in-venue management API port. Default 47990. Resolved to a
	// host-reachable address by the host's generic endpoint reverse-leg, so the same
	// authored step works against a pod's published port and a VM's forwarded one.
	Port int64 `json:"port,omitempty"`

	// token — the management bearer token, inline. Prefer token_file or the default
	// discovery (see the plugin's token resolution order); an inline token in
	// charly.yml is a committed secret.
	Token string `json:"token,omitempty"`

	// token_file — read the bearer token from this path INSIDE the venue. Defaults to
	// ~/.config/punktfunk/mgmt-token, which is where the host writes it at first start.
	TokenFile string `json:"token_file,omitempty"`

	// verify_tls — require a verifiable TLS certificate chain. Deliberately named so the
	// ZERO VALUE is the right default: punktfunk's management API and web console both
	// serve a SELF-SIGNED certificate, so verification fails on every stock host. A
	// bool cannot distinguish "unset" from "false" once gengotypes drops omitempty
	// semantics, so an `insecure?: bool` field could never default to true — this
	// inversion is how the correct default survives the round trip.
	VerifyTLS bool `json:"verify_tls,omitempty"`

	// fingerprint — the paired client this operation targets (rename / access / unpair).
	Fingerprint string `json:"fingerprint,omitempty"`

	// pending_id — the pending device this operation targets (approve / deny).
	PendingID string `json:"pending_id,omitempty"`

	// action_id — the host action to invoke (power.sleep / power.reboot / power.shutdown).
	ActionID string `json:"action_id,omitempty"`

	// provider_id — the library provider or scanner this operation targets.
	ProviderID string `json:"provider_id,omitempty"`

	// name — the new display name for `rename`.
	Name string `json:"name,omitempty"`

	// access — the access preset for `access`.
	Access string `json:"access,omitempty"`

	// pin — the pairing PIN submitted by `pin`.
	Pin string `json:"pin,omitempty"`

	// enabled — the desired state for scanner-toggle.
	Enabled bool `json:"enabled,omitempty"`

	// kinds — an event-kind filter for `events` (e.g. "pairing.*,stream.started").
	Kinds string `json:"kinds,omitempty"`

	// count — how many events `events` waits for before returning. Default 1.
	Count int64 `json:"count,omitempty"`

	// event_timeout — how long `events` waits before giving up. Default 30s.
	EventTimeout string `json:"event_timeout,omitempty"`

	// json_path — a dotted path into the JSON response; when set, the verb's stdout is
	// the value at that path rather than the whole document, so a `stdout:` matcher can
	// assert one field without pattern-matching a blob.
	JSONPath string `json:"json_path,omitempty"`
}
